### ISSUE TITLE
maximize marginal likelihood issue

### ISSUE THREAD

**Issue by kerzmaximilian** [pbenner/gp.regression#1]
`> gp <- new.gp(89.65, kernel.periodic(1,1, 1441))`
`> maximize.marginal.likelihood(gp)`
`[1] Error in as.vector(init) : argument "init" is missing, with no default`

**Comment by pbenner** [comment]
Please have a look at
?maximize.marginal.likelihood.gp

I'll try to make this more user friendly...

**Comment by kerzmaximilian** [comment]
Thanks a lot - My bad for not checking this function!
