### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by rakeshr10** [pbenner/gp.regression#3]
Hi,
    I get this error while installing your package

R CMD INSTALL --no-multiarch ../gp.regression_1.0-1.tar.gz
* installing to library ‘/home/rakesh/WORK/Softwares/Anaconda/lib/R/library’
* installing *source* package ‘gp.regression’ ...
** libs
make[1]: Entering directory '/tmp/Rtmps8KA7k/R.INSTALL3eac3cf58545/gp.regression/src'
gcc -std=gnu99 -I/home/rakesh/WORK/Softwares/Anaconda/lib/R/include -DNDEBUG  -I/home/rakesh/WORK/Softwares/Anaconda/include    -fpic  -I/home/rakesh/WORK/Softwares/Anaconda/include  -c kernel.c -o kernel.o
gcc -std=gnu99 -shared -L/home/rakesh/WORK/Softwares/Anaconda/lib64/R/lib -L/home/rakesh/WORK/Softwares/Anaconda/lib -lgfortran -o gp.regression.so kernel.o -L/home/rakesh/WORK/Softwares/Anaconda/lib64/R/lib -lR
make[1]: Leaving directory '/tmp/Rtmps8KA7k/R.INSTALL3eac3cf58545/gp.regression/src'
installing to /home/rakesh/WORK/Softwares/Anaconda/lib/R/library/gp.regression/libs
** R
Error in .install_package_code_files(".", instdir) : 
files in '/tmp/Rtmps8KA7k/R.INSTALL3eac3cf58545/gp.regression/R' missing from 'Collate' field:
  gp.approximation.stabilized.R
ERROR: unable to collate and parse R files for package ‘gp.regression’
* removing ‘/home/rakesh/WORK/Softwares/Anaconda/lib/R/library/gp.regression’
make: *** [makefile:24: install] Error 1

**Comment by pbenner** [comment]
fixed

**Comment by rakeshr10** [comment]
Thanks was able to install. But I get a warning that there is no 'no-multiarch' option for R CMD build. 

By the way is this package parallelized.

**Comment by pbenner** [comment]
The package itself is not parallelized, but you can use a threaded version of OpenBLAS to speed up linear algebra operations.

Best,
Philipp
